#!/bin/bash
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
fi

function is_ip_address {
  regex="^(0*(1?[0-9]{1,2}|2([0-4][0-9]|5[0-5]))\.){3}0*(1?[0-9]{1,2}|2([‌​0-4][0-9]|5[0-5]))$"
  if [[ $1 =~ $regex ]]; then
    return 0 # success
  else
    return 1 # fail
  fi
}

function add_argument {
  if [ "$first_ip" = false ]; then
    arguments+=","
  else
    first_ip=false
  fi
  arguments+="$1"
}

ip_file="./ip_mappings.txt"
arguments="ip_mappings="
first_ip=true

# Go through each line of the IP addresses file. If it is an IP address, add it, otherwise resolve it as a hostname
while read -r line || [[ -n "$line" ]]; do
  echo "Reading the line: $line"

  if is_ip_address $line; then
    add_argument "\"$line\""

  else
    ip=$(host $line | awk '/has address/ { print $4 ; exit }')

    # Check that hostname has been successfully resolved
    if [[ -n $ip ]]; then
      add_argument "\"$ip\""
    fi
  fi

done < "$ip_file"

echo "$arguments"

# insmod vnic.ko
# ifconfig vnic0 l0
# ifconfig vnic1 l1